# Generated by Django 4.0.5 on 2023-06-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionForEvOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mode_of_payment', models.CharField(choices=[('wallet', 'Wallet'), ('upi', 'Upi'), ('card', 'Card')], max_length=50)),
                ('transaction_status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=50)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wallet')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
