# Generated by Django 4.0.5 on 2023-07-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_transactionforevowner_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mode_of_payment', models.CharField(choices=[('wallet', 'Wallet'), ('upi', 'Upi'), ('card', 'Card')], max_length=50)),
                ('transaction_status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('failed', 'Failed')], max_length=50)),
                ('ev_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_user_transaction', to=settings.AUTH_USER_MODEL)),
                ('station_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='ev_owner_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='station_owner_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.DeleteModel(
            name='TransactionForEvOwner',
        ),
    ]
